package com.github.ovaware.dealmaker.ai;

import com.github.ovaware.dealmaker.config.DealmakerConfigs;
import com.github.ovaware.dealmaker.deal.ConservativeEnglishParser;
import com.github.ovaware.dealmaker.deal.DealPolicy;
import com.github.ovaware.dealmaker.deal.ParseResult;

import java.net.http.HttpClient;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.CompletableFuture;

public final class DealParserRouter {
    private static final ConservativeEnglishParser LOCAL = new ConservativeEnglishParser();

    private DealParserRouter() {}

    public static CompletableFuture<ParseResult> parse(String text) {
        return parse(text, "");
    }

    /** Context is generated by the server, not supplied by the signed book. */
    public static CompletableFuture<ParseResult> parse(String text, String serverContext) {
        List<String> textErrors = DealPolicy.validateText(text);
        if (!textErrors.isEmpty()) return CompletableFuture.completedFuture(new ParseResult(List.of(), textErrors));
        String provider = DealmakerConfigs.server().aiProvider.trim().toUpperCase(Locale.ROOT);
        return switch (provider) {
            case "LOCAL" -> CompletableFuture.completedFuture(LOCAL.parse(text));
            case "GOOGLE_AI_STUDIO", "GOOGLE", "GEMINI" -> new GoogleAiStudioDealParser(httpClient()).parse(text + serverContext)
                    .thenApply(result -> AiContractProtocol.repairBooleanSplit(text, result));
            case "OPENROUTER" -> new OpenRouterDealParser(httpClient()).parse(text + serverContext)
                    .thenApply(result -> AiContractProtocol.repairBooleanSplit(text, result));
            default -> CompletableFuture.completedFuture(ParseResult.rejected("Unknown AI provider: " + provider));
        };
    }

    public static boolean isRemote() {
        return !DealmakerConfigs.server().aiProvider.equalsIgnoreCase("LOCAL");
    }

    private static HttpClient httpClient() {
        return HttpClient.newBuilder()
                .connectTimeout(java.time.Duration.ofSeconds(Math.max(2,
                        Math.min(60, DealmakerConfigs.server().connectTimeoutSeconds))))
                .followRedirects(HttpClient.Redirect.NEVER)
                .build();
    }
}
