modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "OvaWare"
description = '''
A server-authoritative contract and soul-custody addon for Tensura.
'''

[[dependencies.dealmaker]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dealmaker]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dealmaker]]
modId = "tensura"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dealmaker]]
modId = "manascore_skill"
type = "required"
versionRange = "[4.0.0.2,)"
ordering = "AFTER"
side = "BOTH"
